name: Build Angular App to gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Angular build and deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.0
      with:
        github_access_token: ${{ secrets.KEY }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: mercado-de-skins  # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: docs # The folder where your project is supposed to be after running ng build by the action.
